### ISSUE TITLE
Support ignoring headings

### ISSUE THREAD

**Issue by abritinthebay** [remarkjs/remark-autolink-headings#48]
Are you open to an option to ignore certain headings?

I'd really like to ignore h1's for example (as they're generally the top level and basically a post title).

something like `{ ignore: [ 1 ] }` would be perfect.

I have a possible PR but wanted to check if you were open to it.

**Comment by wooorm** [comment]
Hmm, I’m wondering if CSS may do the trick?

**Comment by abritinthebay** [comment]
Well it could (I could turn off pointer events, etc) but that's not great from an accessibility/ARIA/etc point of view. It also wouldn't remove it from the keyboard tab-index navigation.

It would also be nice from a case of it not really being needed for post *titles* as much as the rest of the content.

**Comment by abritinthebay** [comment]
Pretty much all that needs to be changed (other than adding it to defaults as an empty array) is the the `visit` call.

To something like this:
```
const test = node => node.type === 'heading' && !ignore.includes(node.depth);
return ast => visit(ast, test, visitor)
```

**Comment by wooorm** [comment]
> Well it could (I could turn off pointer events, etc) but that's not great from an accessibility/ARIA/etc point of view. It also wouldn't remove it from the keyboard tab-index navigation.

This plugin already really depends on the behaviour of the autolinks: by default ariaHidden is used, and you need CSS to make everything usable in `prepend` mode.

> It would also be nice from a case of it not really being needed for post titles as much as the rest of the content.

To counter this, I like that, on GitHub, you can link to `#readme`, or any H1, and have it go explicitly to that heading.

---

Your issue is about two/three things: a) should it be possible to ignore headings, and either b) the first heading should be ignored or c) it should be possible to ignore headings by depth.

I’m in favour of a), but I don’t think b) or c) makes sense in this library.

For a solution to a), there is a utility called [`unist-util-is`](https://github.com/syntax-tree/unist-util-is), it’s the standardised testing thing in unist/mdast. It could be passed a test (such as `node => node.depth === 1`). In this plugin, we could handle an ignore option like so (pseudocode):

```js
const convert = require('unist-util-is/convert')

// ...

  let {linkProperties, behavior, content, ignore} = {...defaults, ...opts}
  let skip = ignore !== undefined && ignore !== null ? convert(ignore) : false

  // ...

  if (id && (skip === false || !skip(node, index, parent))) {
    method(node, '#' + id)
  }

**Comment by wooorm** [comment]
Are you interested in writing a PR for my above proposal?

**Comment by abritinthebay** [comment]
Ah nice. Yeah, an is-compatible version makes sense.

I can do that PR, sure! May not be until this weekend tho.

**Comment by wooorm** [comment]
Sweet, thanks, and take your time!

**Comment by wooorm** [comment]
Ping! ;)

**Comment by wooorm** [comment]
Closing for now. I’m :+1: to this feature, but it doesn’t seem to be critical.
