### ISSUE TITLE
Include example on how to style <span class="icon icon-link">

### ISSUE THREAD

**Issue by marcofranssen** [remarkjs/remark-autolink-headings#57]
### Subject of the feature

Missing documentation on how to style the link so it is visible.

### Problem

It is unclear on how to style the icon icon-link. Would be good if the readme documents an example on how to style this to have the link show up in front of the headings.

### Expected behavior

Documentation/README shows some example on how to style the icon-links.

### Alternatives

Include an SVG in the span that is rendered by default.

**Comment by ChristianMurphy** [comment]
Using CSS.
The README intentionally does not include a specific example because there are so many different approaches, and css is well outside the scope of the project.
If you're looking for any example, without specifics in mind https://fontawesome.com/v4.7.0/icon/link with https://fontawesome.com/v4.7.0/get-started/#get-started-download is an approach

**Comment by marcofranssen** [comment]
I still think with the out of the box shipped `<span class="icon icon-link"></span>` some css for this should be documented here for easy adoption. Anyhow I will try to replace that with a font-awesome implementation, but that also requires changing the plugin options.

**Comment by songololo** [comment]
@ChristianMurphy appreciate the intent though perhaps just adding what you've said here to the docs would already help clarify the intent and point people in the right direction in terms of understanding the logic involved.
